spring.application.name=Engine

spring.r2dbc.url=postgresql://ep-mute-dawn-a1cgf5c4-pooler.ap-southeast-1.aws.neon.tech
spring.r2dbc.username=neondb_owner
spring.r2dbc.password=npg_7x2UlkNRFJwq

#Execute schema.sql on startup
spring.sql.init.mode=always


#jdbc:postgresql://ep-mute-dawn-a1cgf5c4-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_7x2UlkNRFJwq&sslmode=require&channelBinding=require